### ISSUE TITLE
Suggestion: Add own poster if none available to scrape for show or movie

### ISSUE THREAD

**Issue by kolbdog323** [theMK2k/Media-Hoarder#75] opened 2024-07-29 03:17 UTC
I was thinking you should add an option to add a tv show poster or movie poster via url or upload your own if none available on IMDB to scrape since imdb is very picky on what is allowed and permitted for photos and posters.

Also i do have one more suggestion but I willl create a new post for it

**Comment by kolbdog323** [comment] 2024-07-29 04:21
But this would be useful since some shows and movies don't have posters

**Comment by theMK2k** [comment] 2024-07-29 20:50
duplicate of https://github.com/theMK2k/Media-Hoarder/issues/42

don't worry, this feature will come, but first I want to get the tv series feature out of the beta phase.

**Closed** 2024-07-29 20:50 UTC
