### ISSUE TITLE
Issue: Not scraping anything at all unless imdb in file name or if linked.

### ISSUE THREAD

**Issue by kolbdog323** [theMK2k/Media-Hoarder#66] opened 2024-06-14 17:18 UTC
I tired removing the items rescann then reqadd and rescan and no scraping and imdb scrape check doesnt even show any errors.

**Comment by kolbdog323** [comment] 2024-06-14 17:30
Only scrapes if have imdbid in name just year wont work anymore.

**Comment by kolbdog323** [comment] 2024-06-14 17:55
It wont scrape any movies or shows it does this in the delper preview error only shows the first one or two words of the title if i try to rescan it example tried scraping The Mummy (1999) and in the developer tool view it showed it only  searched the first word " The" then no matches found.

**Comment by kolbdog323** [comment] 2024-06-14 17:56
But it works if i have the imdib in file name or if i directly link to it otherwise it wont find it and i dont want to put the imdbid in every show or movie i want to scrape.

**Comment by kolbdog323** [comment] 2024-06-14 18:03
If its already scaned the tvshow the episodes will still scrape it just wont scrape anyhtjhing new movies or shows unless it has the imdbid or if use the link function.

**Comment by kolbdog323** [comment] 2024-06-14 19:17
Might need to be updated or something  one of the scrapersor the series erorr caused it to fianlly boke after all this time causing it to not scan anything.

**Comment by kolbdog323** [comment] 2024-06-15 14:32
Now wont scrape even with ttid in name

**Comment by kolbdog323** [comment] 2024-06-15 14:34
Any comment about this issue?

**Comment by theMK2k** [comment] 2024-06-15 14:54
I'm off today, will investigate as soon as I return. How does the scraper check look like for you right now?

**Comment by kolbdog323** [comment] 2024-06-15 14:58
Working no errors except for series. But titles will only scrape if have the imdbid in the file name or if i link to it otherwise wont scrape if only have year.

**Comment by kolbdog323** [comment] 2024-06-15 15:06
Episodes will scrape if already added the show just wont scrape new movies or tvshows with only the year or years just with imdbid.

**Comment by kolbdog323** [comment] 2024-06-15 19:34
Its seems by deleting the unistall registry in regedit and reinstalling media hoarder fixed it.

**Comment by kolbdog323** [comment] 2024-06-15 20:00
Never mind the issue is back.

**Comment by kolbdog323** [comment] 2024-06-15 20:03
It just scans and adds it to library but no actaul imdb scraping.

**Comment by kolbdog323** [comment] 2024-06-15 20:10
Example just tried scraping Forged in Fire. I tried FOred in Fire, and Forged in Fire(2015-) Didnt scrape but once i added the Forged in Fire (2015-) [tt4680444] It will scrape. same with any movie or tv show have to put in the ttid othrwise won't scrape.

**Comment by theMK2k** [comment] 2024-06-15 20:49
Thanks.

The IMDB Scraping process has two phases:

1/ Detection

2/ Scraping

During the **detection** phase, Media Hoarder tries to find the correct IMDB entry to your media. Of course, if the filename / directory name contains the tt* this task is trivial and Media Hoarder doesn't have to do anything but assume the tt* is correct and move on with phase 2.

If the filename / directory name has no tt*, Media Hoarder tries to find the correct IMDB entry by running a search on the IMDB site with some of the words of the filename / directory name (the stuff you also saw in the logs of the developer tools).

I highly suspect that currently something doesn't work with IMDB search during phase 1. It also looks like Media Hoarder currently does not provide enough info when this fails alltogether.

I will investigate this and let you know.

**Comment by kolbdog323** [comment] 2024-06-15 20:52
Thanks not sure why will only scrape if have tt* in folder name or file name now it was working a couple days ago normally.

**Comment by kolbdog323** [comment] 2024-06-15 20:56
It will scrape as long as the tt* is in the name even for special episodes. But if a show is already added it will scrape all episodes normally with no tt* needed for any new episodes. But the movie and tv shows all require tt* now in the name otherwise won't scrape otherwise i have to link the show or movie once it is added if don't put tt* in name.

**Comment by theMK2k** [comment] 2024-06-15 21:08
Oh yes, that's right.

For a TV show episode it's a bit different:

Scraping a TV show episode's data relies on the fact that the IMDB entry is already correctly detected for the show (not the episode), then Media Hoarder looks up the episodes list of the show and matches that against the season and episode number provided in the episode's filename.

**Comment by theMK2k** [comment] 2024-06-15 21:18
getting closer...

I just created a `Avengers - Endgame [2019].mkv` and can reproduce what you reported: the detection of the IMDB entry fails (with an error):

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/20d70224-efa3-4f26-b2e9-d6ea1a5ff35f)

**Comment by kolbdog323** [comment] 2024-06-15 21:20
That is exactly what i got in the developer tools just not in the offical imdb scaping checker shows no erros.

> getting closer...
> 
> I just created a `Avengers - Endgame [2019].mkv` and can reproduce what you reported: the detection of the IMDB entry fails (with an error):
> 
> ![image](https://private-user-images.githubusercontent.com/16878526/340035059-20d70224-efa3-4f26-b2e9-d6ea1a5ff35f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0ODY2NzEsIm5iZiI6MTcxODQ4NjM3MSwicGF0aCI6Ii8xNjg3ODUyNi8zNDAwMzUwNTktMjBkNzAyMjQtZWZhMy00ZjI2LWIyZTktZDZlYTFhNWZmMzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDIxMTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NDIyZDQwZjJhYzM3ZDkyZTc3NWM4OWZhY2FkNjBkNDIyYmU4ZTFlOGJjYTRmYzRlMzgwOTVkYTk4YjUzNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SexHOD5zHh8wtX1_AySo_scjnMLkatfJxKbTo_2lfg4)

**Comment by kolbdog323** [comment] 2024-06-15 21:35
But mine went futher then that it showed this for the error as well: imdb-scraper.js:2036 [scrapeIMDBFindPageSearchV3] ERROR: Error: GraphQL Error: PersistedQueryNotFound
    at h (imdb-scraper.js:116)
    at x (imdb-scraper.js:1988)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async c (find-imdb-tconst.js:145)
    at async Ee (store.js:2899)
    at async De (store.js:2625)
    at async ye (store.js:2561)
    at async X (store.js:423)

**Comment by theMK2k** [comment] 2024-06-15 21:44
Good, the culprit has been found, IMDB indeed have updated the "find" function (and Media Hoarder uses this to detect the IMDB entries for a file/directory without tt* in its name).

So I had to provide an update for that, which I just did. Please restart Media Hoarder and the update will be fetched automatically.

Please re-test and let me know how it went.

I will create a new beta release later that includes the "find" function in the Scraper checks, too.

**Comment by kolbdog323** [comment] 2024-06-15 21:48
Does that work for the portable version resetting it as well? Since i reset it and it is working again not sure if that will work for the portable version as well.

**Comment by theMK2k** [comment] 2024-06-15 21:49
yes, every version (stable, beta, portable or installed) fetch the latest IMDB function definitions

**Comment by kolbdog323** [comment] 2024-06-15 21:55
It will take some time to rescrape all of the movies and shows I have since I had to delete Media Hoarder because I thought the version I had was the problem. Thank you for fixing it again.

**Comment by theMK2k** [comment] 2024-06-15 22:01
Thank **you** for helping in making Media Hoarder better :)

**Comment by kolbdog323** [comment] 2024-06-15 22:02
No problem. Even though I'm not a programmer I'm glad I can help in anyway I can even though some of the suggestions I make are not doable.

**Comment by theMK2k** [comment] 2024-06-16 10:53
As promised, an updated beta **v1.4.0-b4** is released: https://github.com/theMK2k/Media-Hoarder/releases/tag/v1.4.0-b

I'll close this issue now, please re-open if there are still problems.

**Closed by theMK2k** 2024-06-16 10:53 UTC
