### ISSUE TITLE
Scan Media wrong number added

### ISSUE THREAD

**Issue by kolbdog3333** [theMK2k/Media-Hoarder#45] opened 2024-01-25 23:15 UTC
Can you please fix it when it scans the media and adds it it doesn't show a higher amount than what is added for example if I add one series and 1 episode it shows one series was added but it shows 2 episodes were added which is incorrect same with movies sometimes it shows one or two numbers higher then what it is

**Comment by theMK2k** [comment] 2024-01-26 08:29
You mean the result (green popup after the scan)?

**Comment by theMK2k** [comment] 2024-01-26 08:31
If so, the issue is already known and will be fixed in the future: https://github.com/theMK2k/Media-Hoarder/blob/feature-series/TODO.md

> revisit the rescan summary (the numbers are mostly wrong)

**Comment by kolbdog3333** [comment] 2024-01-26 17:11
Thanks didn't realize that

**Comment by theMK2k** [comment] 2024-01-26 18:02
all good, it's buried in a wall of TODOs :)

**Comment by theMK2k** [comment] 2024-04-08 19:48
@kolbdog3333, @kolbdog323

The rescan summary has been reworked and includes a lot more information now. Also the Settings section has a new tab with the scan history. v1.4.0-b3 is released, enjoy!

https://github.com/theMK2k/Media-Hoarder/releases/edit/v1.4.0-b

I'm closing this ticket now, feel free to re-open if the issue is still unresolved.

**Closed by theMK2k** 2024-04-08 19:48 UTC
