### ISSUE TITLE
New imdb scraper check error for Release info

### ISSUE THREAD

**Issue by kolbdog323** [theMK2k/Media-Hoarder#64] opened 2024-06-10 14:19 UTC
I was just runing a scraper check today and thuis new error appeared for the Release info:
EXCEPTION: { "stack": "Error: GraphQL Error: PersistedQueryNotFound\n at h (app://./js/app.c94a5570.js:1:804077)\n at y (app://./js/app.c94a5570.js:1:813713)\n at processTicksAndRejections (internal/process/task_queues.js:93:5)\n at async Module.v (app://./js/app.c94a5570.js:1:811143)\n at async h (app://./js/app.c94a5570.js:1:115806)\n at async o.runChecks (app://./js/app.c94a5570.js:1:492064)", "message": "GraphQL Error: PersistedQueryNotFound" }

**Comment by theMK2k** [comment] 2024-06-10 14:52
Thanks, this can be the reason for your other issue: https://github.com/theMK2k/Media-Hoarder/issues/63

Running the IMDB scraper checks on my end, I don't get these errors. I suspect that IMDB is sometimes providing (slightly) different pages and backend functions based on the regions the user comes from.

I expect:

either the current error will arrive on my end too, so I can create a fix

or

the error will vanish on your side

**Comment by kolbdog323** [comment] 2024-06-10 15:51
Its fixed somewhat. For some reason the year of the folder name got into the actul name of the show. It works whnen i do the portable version no issues its jsut whe windows version that is doing it.

**Comment by kolbdog323** [comment] 2024-06-14 04:38
Im getting this error for imdb ratings now: $IMDB_id_AgeRating_Chosen_Country missing

I've scraped checked 5 times in row same error . Causing it not to properly scrape anything

**Comment by kolbdog323** [comment] 2024-06-14 06:33
> Im getting this error for imdb ratings now: $IMDB_id_AgeRating_Chosen_Country missing
> 
> I've scraped checked 5 times in row same error . Causing it not to properly scrape anything

Its not even scraping anything now .

**Comment by theMK2k** [comment] 2024-06-14 06:55
Do you have more details? Can you provide a screenshot of the IMDB Scraper Check?

**Comment by kolbdog323** [comment] 2024-06-14 07:01
Was down for 2 hours not correctly scraping seems error is gone now.

**Comment by theMK2k** [comment] 2024-06-14 07:10
That's a relief. How does your IMDB Scraper Check look now? All green?

**Comment by kolbdog323** [comment] 2024-06-14 07:13
Never mind back again and not showing any errors now just not properly scraping or cuts off in middle of it.

**Comment by theMK2k** [comment] 2024-06-14 07:31
I suspect IMDB are rolling out some updates and they might do it on a per-region basis (my IMDB Scraper Check is all green all the time).

Another possibility is your internet connection might be unstable or IMDB has implemented counter-measures for scraping.

I will run a larger scraping later to check if I can reproduce the issues you face.

**Comment by kolbdog323** [comment] 2024-06-14 07:31
> Never mind back again and not showing any errors now just not properly scraping or cuts off in middle of it.

Its fixed now had to remove the files and re-add them sorry for worrying you.

**Comment by theMK2k** [comment] 2024-06-14 07:41
OK, thanks, I'll close this issue now :)

**Closed by theMK2k** 2024-06-14 07:41 UTC
