### ISSUE TITLE
Bug: Only looks at the first year for tv series ignores the end year.

### ISSUE THREAD

**Issue by kolbdog323** [theMK2k/Media-Hoarder#70] opened 2024-06-27 13:48 UTC
I noticed for some shows it doesnt search both years example i did this show Pippi Longstocking (1997-1998).
It ignored the end year 1998 since it found a movie relased the same year 1997 it doesnt search both years 1997 and 1998. Just the first year it does that for any show it seems only looks for the first year not start to end year.

 I added that show for my neice. I had to add the ttid to folder name to scrape correctly. 

Sorry for the rambling.

**Comment by theMK2k** [comment] 2024-06-27 19:58
I'd file this as a duplicate of https://github.com/theMK2k/Media-Hoarder/issues/61

the IMDB detection is still not good enough and should prefer tv-series to movies

**Comment by kolbdog323** [comment] 2024-06-27 20:02
How is that a duplicate when this is a tv series not a movie?

**Comment by kolbdog323** [comment] 2024-06-27 20:03
This is a diffent bug. the other one was a movie as a series. This is a series as a movie or incorrect series.

**Comment by kolbdog323** [comment] 2024-06-27 20:04
It shows the incorrect series or it identities it as a movie it ignores the end date.

**Comment by kolbdog323** [comment] 2024-06-27 20:05
The other bug was if no year was in the movie name this one it ignores the end year and only looks at the first year. This (1997) It ignores the (-) separating the two years to show the full year.

**Comment by theMK2k** [comment] 2024-06-27 20:09
When you do a rescan and Media Hoarder is working on a tv-series and it uses the IMDB search to detect the correct IMDB entry, it should prefer the tv-series to the movie.

Both are found when the search runs with "Pippi Longstocking 1997":

the series: https://www.imdb.com/title/tt0163482/
the movie: https://www.imdb.com/title/tt0119899/

So your issue would already be resolved if Media Hoarder would pick the tv-series instead of the movie.

That's what I meant with duplicate. Because I understand https://github.com/theMK2k/Media-Hoarder/issues/61 is the same problem.

Another note: a search for Pippi Longstocking 1997-1998 wouldn't help either because it yields the same results.

A search for Pippi Longstocking 1998 wouldn't help as well, neither the series nor the movie would come up as a result.

**Comment by kolbdog323** [comment] 2024-06-27 20:12
SOrry didnt mean to go off. It was just annoying since that show was for my niece and it incorrectly scraped it as one.

**Comment by kolbdog323** [comment] 2024-06-27 20:19
It looks like in the imdb search it shows the full years if you push enter since it showed both tv show and seires correctlly this: https://www.imdb.com/find/?q=pippi%20longstocking%201997-1998&ref_=nv_sr_sm           Since it shows the movie and series the years exactly how it should be.

**Comment by kolbdog323** [comment] 2024-06-27 20:42
Sorry don't mean to keep rambling.

**Comment by kolbdog323** [comment] 2024-06-27 21:16
Ill close this sinve a duplicate of #61

**Closed** 2024-06-27 21:16 UTC

**Comment by theMK2k** [comment] 2024-06-27 21:20
> SOrry didnt mean to go off. It was just annoying since that show was for my niece and it incorrectly scraped it as one.

I understand your issue and we'll have an optimized IMDB detection in the near future :)
